FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

# Копируем исходники (в docker-compose смонтируем нужную папку)
COPY . .

CMD ["npx", "ts-node", "worker.ts"]
