# Базовый образ Node.js
FROM node:20-alpine

# Создаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json (или pnpm/yarn.lock)
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install --production

# Копируем весь код worker (в docker-compose будет build.context каждой PLC)
COPY . .

# Запуск worker
CMD ["node", "worker.js"]
